---
title: "Final Project Report"
author: "Andrew Casey & Ciara Virgo"
date: "Due April 30, 2019"
output: html_notebook
---

```{r echo=TRUE, message=FALSE}
# always clean up R environment
rm(list = ls())

# loading packages
library(plyr)
library(mdsr)
library(tidyr)
library(data.table)
library(stringr)
library(ggplot2)
library(tibble)
library(klaR)
library(Rmixmod)

# loading in data
Heart_Raw <- fread("NCHS_-_Potentially_Excess_Deaths_from_the_Five_Leading_Causes_of_Death.csv")
Tobacco_Raw <- fread("Behavioral_Risk_Factor_Data__Tobacco_Use__2010_And_Prior_.csv")
```


# Data Wrangling

```{r}
#Filter the Smoking Data to narrow it down to 3 States and years common between the two data sets
#Also remove all, but the necessary columns
HeartData <-
  Heart_Raw %>%
  dplyr::select(Year, `Cause of Death`, State, `Age Range`, Locality, `Observed Deaths`, Benchmark) %>%
  filter(`Cause of Death` == "Heart Disease") %>%
  filter(State %in% c("Pennsylvania", "Texas", "Washington")) %>%
  filter(Year %in% c(2005, 2006, 2007, 2008, 2009, 2010)) %>%
  filter(Locality %in% c("Metropolitan", "Nonmetropolitan")) %>%
  filter(Benchmark %in% c("2005 Fixed"))

#Filter the Heart Disease Data to narrow it down to 3 states and years common between the two data sets
#Also remove all, but the necessary columns
TobaccoData <-
  Tobacco_Raw %>%
  dplyr::select(YEAR, LocationDesc, TopicType, TopicDesc, MeasureDesc, Sample_Size, Gender, Race, Age, Education) %>%
  setnames(old=c("YEAR","LocationDesc", "Age"), new=c("Year", "State", "Age Range")) %>%
  filter(State %in% c("Pennsylvania", "Texas", "Washington")) %>%
  filter(Year %in% c(2005, 2006, 2007, 2008, 2009, 2010))

#Remove the rows that contain Male and Female, so there are only rows with Overall.
Rows1 <- TobaccoData$Gender=="Overall"
TobaccoData <- TobaccoData[Rows1,]

#Remove the rows that contain All Ages for the age range
Rows2 <- TobaccoData$`Age Range`=="All Ages"
TobaccoData <- TobaccoData[Rows2==FALSE,]

#Remove the rows that have anything but All Grades as the education level
Rows3 <- TobaccoData$Education=="All Grades"
TobaccoData <- TobaccoData[Rows3,]

TobaccoData <-
  TobaccoData %>%
  dplyr::select(-c(7,8,10))

#Changes the Sample Size column to numeric variables
TobaccoData$Sample_Size <- as.numeric(gsub(",", "", TobaccoData$Sample_Size))
TobaccoData$Sample_Size <- as.numeric(as.character(TobaccoData$Sample_Size))
```

```{r}
#Changes the labels of the Age Ranges in both data sets so they are common
for(i in 1:length(HeartData$`Age Range`)){
  if(HeartData$`Age Range`[i] == "0-49"){
    HeartData$`Age Range`[i] <- c("44 Years and Below")
  }
  else if(HeartData$`Age Range`[i] == "0-54"){
    HeartData$`Age Range`[i] <- c("45 to 64 Years")
  }
  else if(HeartData$`Age Range`[i] == "0-59"){
    HeartData$`Age Range`[i] <- c("45 to 64 Years")
  }
  else if(HeartData$`Age Range`[i] == "0-64"){
    HeartData$`Age Range`[i] <- c("45 to 64 Years")
  }
  else if(HeartData$`Age Range`[i] == "0-69"){
    HeartData$`Age Range`[i] <- c("65 Years and Older")
  }
  else if(HeartData$`Age Range`[i] == "0-74"){
    HeartData$`Age Range`[i] <- c("65 Years and Older")
  }
  else if(HeartData$`Age Range`[i] == "0-79"){
    HeartData$`Age Range`[i] <- c("65 Years and Older")
  }
  else if(HeartData$`Age Range`[i] == "0-84"){
    HeartData$`Age Range`[i] <- c("65 Years and Older")
  }
}
for(i in 1:length(TobaccoData$`Age Range`)){
  if(TobaccoData$`Age Range`[i] == "18 to 24 Years"){
    TobaccoData$`Age Range`[i] <- c("44 Years and Below")
  }
  else if(TobaccoData$`Age Range`[i] == "25 to 44 Years"){
    TobaccoData$`Age Range`[i] <- c("44 Years and Below")
  }
}
```

```{r}
#Function that makes the data longer by duplicating the number of rows by the value in the sample size column and making the data set have more rows.
TobaccoCasestoRows <- function(){
  Year <- vector()
  State <- vector()
  TopicType <- vector()
  TopicDesc <- vector()
  MeasureDesc <- vector()
  AgeRange <- vector()
  for (i in 1:length(TobaccoData$Sample_Size)){
    Year <- c(Year, rep(TobaccoData$Year[i], TobaccoData$Sample_Size[i]))
    State <- c(State, rep(TobaccoData$State[i], TobaccoData$Sample_Size[i]))
    TopicType <- c(TopicType, rep(TobaccoData$TopicType[i], TobaccoData$Sample_Size[i]))
    TopicDesc <- c(TopicDesc, rep(TobaccoData$TopicDesc[i], TobaccoData$Sample_Size[i]))
    MeasureDesc <- c(MeasureDesc, rep(TobaccoData$MeasureDesc[i], TobaccoData$Sample_Size[i]))
    AgeRange <- c(AgeRange, rep(TobaccoData$`Age Range`[i], TobaccoData$Sample_Size[i]))
  }
  df <- data.frame(Year, State, TopicType, TopicDesc, MeasureDesc, AgeRange)
  return(df)
}
Tobacco <- TobaccoCasestoRows()
```

```{r}
#Function that makes the data longer by duplicating the number of rows by the value in the sample size column and making the data set have more rows.
HeartCasestoRows <- function(){
  Year <- vector()
  State <- vector()
  AgeRange <- vector()
  Locality <- vector()
  for (i in 1:length(HeartData$`Observed Deaths`)){
    Year <- c(Year, rep(HeartData$Year[i], HeartData$`Observed Deaths`[i]))
    State <- c(State, rep(HeartData$State[i], HeartData$`Observed Deaths`[i]))
    Locality <- c(Locality, rep(HeartData$Locality[i], HeartData$`Observed Deaths`[i]))
    AgeRange <- c(AgeRange, rep(HeartData$`Age Range`[i], HeartData$`Observed Deaths`[i]))
  }
  df <- data.frame(Year, State, Locality, AgeRange)
  return(df)
}
Heart <- HeartCasestoRows()
```

```{r}
#Picking out observations that include the letters YEARS.
Heart_age <- 
  HeartData %>%
  select(`Age Range`)

grep("[YEARS]", Heart_age, value = TRUE)
```


# Data Visualization

### Data Wrangling for plots A and B.
```{r}
#Select desired variables from Tobacco.
Tobacco_Measure <- Tobacco %>%
  select(Year, State, MeasureDesc, AgeRange)

#Adding a measure descriptor variable and selecting desired variables from Heart.
Heart_Measure <- Heart %>%
  add_column(MeasureDesc = "Heart Disease") %>%
  select(Year, State, MeasureDesc, AgeRange)
  
#Bind the two datasets together.
TobaccoHeart <- rbind(Tobacco_Measure, Heart_Measure)
```

```{r}
#Calculating percentages
#We did this so that our graphs aren't taken over by the large sample size of the Heart data set. If we don't use percentages, it would look like there were more individuals with heart disease in each state relative to their number of smokers. But in reality, the large number would just be because of the bigger sample. 

TobaccoHeartTable <- TobaccoHeart %>%
  #Count the number of unique rows.
  count(Year, State, MeasureDesc, AgeRange) %>%
  #Split momentarily into Tobacco and Heart again.
  group_by(MeasureDesc) %>%
  #Find the percentage of each unique "grouping" within each original dataset.
  mutate(Frequency = n / sum(n)) %>% 
  #Split into Tobacco and Heart but this time also split by state.
  group_by(MeasureDesc, State) %>%
  #Find the percentage of each grouping relative to the state it belongs to in the original dataset.
  mutate(FrequencyByState = n / sum(n))
```


### (A) Plot A uses both data sets.
```{r}
#Plot shows the count of people who currenlty smoke and have died from heart disease by age groups across Pennsylvania, Texas, and Washington.
ggplot(TobaccoHeartTable, aes(x = MeasureDesc, y = n, fill = MeasureDesc)) + 
  geom_boxplot() +
  facet_wrap(~ AgeRange, ncol = 3) +
  ggtitle("Number of people who currently smoke or have died from heart disease by age") +
  labs(fill = "Condition") +
  xlab("Condition") +
  ylab("Count of people")
```


### (B) Plot B uses 3 or more variables.
```{r}
#Plot the percentage of current smokers and heart disease of each state by year. 
ggplot() + 
  geom_bar(data=TobaccoHeartTable, 
           aes(y = FrequencyByState, x = Year, fill = MeasureDesc), 
           stat="identity",
           position='stack') +
  theme_bw() +
  facet_grid(AgeRange ~ State) +
  labs(fill = "Condition") +
  ggtitle("Percentage of current smokers and heart disease deaths by state from 2005 - 2010")
```


### (C) Third visualization
```{r}
#Plot the count of current smokers by state across all years and all age groups 
ggplot(Tobacco_Measure, aes(x = Year)) +
  geom_histogram(stat = "count") +
  geom_bar(aes(fill = State)) +
  ggtitle("Number of current smokers by state between 2005 - 2010") +
  ylab("Number of smokers")
```

### (D) Fourth visualization
```{r}
#Plot the count of heart disease deaths by state across all years and all age groups. 
 ggplot(Heart_Measure, aes(x = Year)) +
  geom_histogram(stat = "count") +
  geom_bar(aes(fill = State)) +
  ggtitle("Number of people who have died of heart disease by state between 2005 - 2010") +
  labs(fill = "Condition") +
  xlab("Condition") +
  ylab("Count of people")
```


# Data Analysis

### Supervised Learning and Simulation
```{r}
#Changes the categorical variables to quantitative so we can do a linear regression model.
HeartModelData <- HeartData
for(i in 1:length(HeartModelData$`Age Range`)){
  if(HeartModelData$`Age Range`[i] == "44 Years and Below"){
    HeartModelData$`Age Range`[i] <- 0
  }
  else if(HeartModelData$`Age Range`[i] == "45 to 64 Years"){
    HeartModelData$`Age Range`[i] <- 1
  }
  else if(HeartModelData$`Age Range`[i] == "65 Years and Older"){
    HeartModelData$`Age Range`[i] <- 2
  }
}

for(i in 1:length(HeartModelData$`Age Range`)){
  if(HeartModelData$Locality[i] == "Nonmetropolitan"){
    HeartModelData$Locality[i] <- 0
  }
  else if(HeartModelData$Locality[i] == "Metropolitan"){
    HeartModelData$Locality[i] <- 1
  }
}

for(i in 1:length(HeartModelData$State)){
  if(HeartModelData$State[i] == "Pennsylvania"){
    HeartModelData$State[i] <- 0
  }
  else if(HeartModelData$State[i] == "Texas"){
    HeartModelData$State[i] <- 1
  }
  else if(HeartModelData$State[i] == "Washington"){
    HeartModelData$State[i] <- 2
  }
}
```

```{r}
#Multiple Linear Regression model coefficients
linearMod <- lm(`Observed Deaths` ~ Locality + `Age Range`, data = HeartModelData)
summary(linearMod)
```

```{r}
#Final Simulation of the multiple linear regression model made above.
n <- 1000
x1 <- runif(n, min = 0, max = 1)
x2 <- runif(n, min = 0, max = 2)
x3 <- runif(n, min = 0, max = 2)
sim <- function(beta0 = -1831.4, beta1 = 5038.4, beta2 = 1241.5, beta3 = 5168.5){
  y <- beta0 + beta1*x1 + beta2*x2 + beta3*x3 + rnorm(n, mean = mean(HeartModelData$`Observed Deaths`),
                                                      sd = sd(HeartModelData$`Observed Deaths`))
  mod <- lm(y ~ x1 + x2 + x3)
  result <- coefficients(mod)
  return(result)
}
sims <- mosaic::do(1000) * sim()
sims
```


### Unsupervised Learning
```{r}
#Selecting data to use in clusters
HeartModelData <-
  HeartModelData %>%
  select(`Age Range`, Locality, State)
#Using kmodes technique to cluster data
KResults <- kmodes(HeartModelData, 10, iter.max = 10, weighted = FALSE)
KResults
#Plotting kmodes clusters to get a clear visualization on the data
plot(HeartModelData[],col= KResults$cluster)
```



